### ISSUE TITLE
Prevision

### ISSUE THREAD

**Issue by Zeug-9** [blossom/nest#3]
Hello,
I am currently working with Liquid Boris Kaul
What is your prediction?

**Comment by tosh** [comment]
I'm currently looking into what our future stack can look like (for mobile as well as desktop).
I hope I'll have something to share in a few days. What are your thoughts on react-dart?

**Comment by Zeug-9** [comment]
I looked-dart react quickly.
It has a dependency on the library react.js
Exits to the dart as well do it completely.
I prefer to use Liquid and VCSs which leaves us a good freedom

**Comment by tosh** [comment]
What is VCS?

Do you use a certain architecture for data flow like flux?
Any examples you can share?

**Comment by Zeug-9** [comment]
Virtual CSS Library

**Comment by Zeug-9** [comment]
Now i use it as component to sites with drupal but also for webapp

**Comment by Zeug-9** [comment]
Flux is interesting for its architecture
Have you tried https://github.com/marcojakob/dart-event-bus

**Comment by Zeug-9** [comment]
Hi,
Have you a date for your first release?
I would be happy to make tests

**Comment by tosh** [comment]
Thanks for the pointers, I hope to have something to look at in a few days :)

**Comment by Zeug-9** [comment]
so wait and see
